// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DeleteFromLocal_Stream.proto

package StorageMaintainerMessage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//stream请求结构
type StreamReqData struct {
	StrChannelID         string   `protobuf:"bytes,1,opt,name=strChannelID,proto3" json:"strChannelID,omitempty"`
	StrRelativePath      string   `protobuf:"bytes,2,opt,name=strRelativePath,proto3" json:"strRelativePath,omitempty"`
	StrMountPoint        string   `protobuf:"bytes,3,opt,name=strMountPoint,proto3" json:"strMountPoint,omitempty"`
	StrDate              string   `protobuf:"bytes,4,opt,name=strDate,proto3" json:"strDate,omitempty"`
	StrRecordID          string   `protobuf:"bytes,5,opt,name=strRecordID,proto3" json:"strRecordID,omitempty"`
	NStartTime           int64    `protobuf:"varint,6,opt,name=nStartTime,proto3" json:"nStartTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamReqData) Reset()         { *m = StreamReqData{} }
func (m *StreamReqData) String() string { return proto.CompactTextString(m) }
func (*StreamReqData) ProtoMessage()    {}
func (*StreamReqData) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a0fc7b93e9382d, []int{0}
}

func (m *StreamReqData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamReqData.Unmarshal(m, b)
}
func (m *StreamReqData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamReqData.Marshal(b, m, deterministic)
}
func (m *StreamReqData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamReqData.Merge(m, src)
}
func (m *StreamReqData) XXX_Size() int {
	return xxx_messageInfo_StreamReqData.Size(m)
}
func (m *StreamReqData) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamReqData.DiscardUnknown(m)
}

var xxx_messageInfo_StreamReqData proto.InternalMessageInfo

func (m *StreamReqData) GetStrChannelID() string {
	if m != nil {
		return m.StrChannelID
	}
	return ""
}

func (m *StreamReqData) GetStrRelativePath() string {
	if m != nil {
		return m.StrRelativePath
	}
	return ""
}

func (m *StreamReqData) GetStrMountPoint() string {
	if m != nil {
		return m.StrMountPoint
	}
	return ""
}

func (m *StreamReqData) GetStrDate() string {
	if m != nil {
		return m.StrDate
	}
	return ""
}

func (m *StreamReqData) GetStrRecordID() string {
	if m != nil {
		return m.StrRecordID
	}
	return ""
}

func (m *StreamReqData) GetNStartTime() int64 {
	if m != nil {
		return m.NStartTime
	}
	return 0
}

//stream返回结构
type StreamResData struct {
	StrChannelID         string   `protobuf:"bytes,1,opt,name=strChannelID,proto3" json:"strChannelID,omitempty"`
	NRespond             int32    `protobuf:"varint,2,opt,name=nRespond,proto3" json:"nRespond,omitempty"`
	StrRecordID          string   `protobuf:"bytes,3,opt,name=strRecordID,proto3" json:"strRecordID,omitempty"`
	StrDate              string   `protobuf:"bytes,4,opt,name=strDate,proto3" json:"strDate,omitempty"`
	StrMountPoint        string   `protobuf:"bytes,5,opt,name=strMountPoint,proto3" json:"strMountPoint,omitempty"`
	NStartTime           int64    `protobuf:"varint,6,opt,name=nStartTime,proto3" json:"nStartTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamResData) Reset()         { *m = StreamResData{} }
func (m *StreamResData) String() string { return proto.CompactTextString(m) }
func (*StreamResData) ProtoMessage()    {}
func (*StreamResData) Descriptor() ([]byte, []int) {
	return fileDescriptor_08a0fc7b93e9382d, []int{1}
}

func (m *StreamResData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResData.Unmarshal(m, b)
}
func (m *StreamResData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResData.Marshal(b, m, deterministic)
}
func (m *StreamResData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResData.Merge(m, src)
}
func (m *StreamResData) XXX_Size() int {
	return xxx_messageInfo_StreamResData.Size(m)
}
func (m *StreamResData) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResData.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResData proto.InternalMessageInfo

func (m *StreamResData) GetStrChannelID() string {
	if m != nil {
		return m.StrChannelID
	}
	return ""
}

func (m *StreamResData) GetNRespond() int32 {
	if m != nil {
		return m.NRespond
	}
	return 0
}

func (m *StreamResData) GetStrRecordID() string {
	if m != nil {
		return m.StrRecordID
	}
	return ""
}

func (m *StreamResData) GetStrDate() string {
	if m != nil {
		return m.StrDate
	}
	return ""
}

func (m *StreamResData) GetStrMountPoint() string {
	if m != nil {
		return m.StrMountPoint
	}
	return ""
}

func (m *StreamResData) GetNStartTime() int64 {
	if m != nil {
		return m.NStartTime
	}
	return 0
}

func init() {
	proto.RegisterType((*StreamReqData)(nil), "StorageMaintainerMessage.StreamReqData")
	proto.RegisterType((*StreamResData)(nil), "StorageMaintainerMessage.StreamResData")
}

func init() { proto.RegisterFile("DeleteFromLocal_Stream.proto", fileDescriptor_08a0fc7b93e9382d) }

var fileDescriptor_08a0fc7b93e9382d = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xdf, 0x4a, 0x42, 0x41,
	0x10, 0xc6, 0x5b, 0x4d, 0xcd, 0x29, 0x09, 0xf6, 0x6a, 0x91, 0x08, 0x39, 0x04, 0x9d, 0x2b, 0x91,
	0x7a, 0x82, 0xe8, 0x90, 0x08, 0x09, 0x72, 0xec, 0x3e, 0x26, 0x1d, 0xf4, 0xc0, 0xba, 0x6b, 0xb3,
	0x63, 0x4f, 0xd6, 0x8b, 0xf4, 0x04, 0xbd, 0x4a, 0xb4, 0x52, 0xf8, 0x27, 0xc9, 0x1b, 0x2f, 0xe7,
	0x9b, 0x8f, 0x9d, 0xf9, 0x7d, 0xc3, 0xc2, 0x45, 0x46, 0x96, 0x84, 0x1e, 0xd8, 0xcf, 0x1e, 0xfd,
	0x08, 0xed, 0xf3, 0x50, 0x98, 0x70, 0xd6, 0x9e, 0xb3, 0x17, 0xaf, 0xcd, 0x50, 0x3c, 0xe3, 0x84,
	0xfa, 0x58, 0x38, 0xc1, 0xc2, 0x11, 0xf7, 0x29, 0x04, 0x9c, 0x50, 0xf2, 0xa9, 0xa0, 0xb1, 0xb4,
	0xe6, 0xf4, 0x9a, 0xa1, 0xa0, 0x4e, 0xe0, 0x2c, 0x08, 0xdf, 0x4f, 0xd1, 0x39, 0xb2, 0xbd, 0xcc,
	0xa8, 0x96, 0x4a, 0xeb, 0xf9, 0x9a, 0xa6, 0x53, 0x38, 0x0f, 0xc2, 0x39, 0x59, 0x94, 0xe2, 0x8d,
	0x06, 0x28, 0x53, 0x53, 0x8a, 0xb6, 0x4d, 0x59, 0x5f, 0x41, 0x23, 0x08, 0xf7, 0xfd, 0xc2, 0xc9,
	0xc0, 0x17, 0x4e, 0x4c, 0x39, 0xfa, 0xd6, 0x45, 0x6d, 0xa0, 0x16, 0x84, 0x33, 0x14, 0x32, 0xc7,
	0xb1, 0xff, 0x53, 0xea, 0x16, 0x9c, 0xc6, 0x27, 0x47, 0x9e, 0xc7, 0xbd, 0xcc, 0x54, 0x62, 0x77,
	0x55, 0xd2, 0x97, 0x00, 0x6e, 0x28, 0xc8, 0xf2, 0x54, 0xcc, 0xc8, 0x54, 0x5b, 0x2a, 0x2d, 0xe7,
	0x2b, 0x4a, 0xf2, 0xb1, 0x42, 0x18, 0xf6, 0x26, 0x6c, 0xc2, 0x89, 0xcb, 0x29, 0xcc, 0xbd, 0x1b,
	0x47, 0xb4, 0x4a, 0xfe, 0x5b, 0x6f, 0xee, 0x54, 0xde, 0xde, 0x69, 0x37, 0xcf, 0x56, 0x1e, 0x95,
	0xbf, 0xf2, 0xf8, 0x87, 0xe9, 0xe6, 0xbd, 0x04, 0xb5, 0x2e, 0x13, 0x09, 0xb1, 0x46, 0xa8, 0x77,
	0x49, 0x96, 0x84, 0xfa, 0xba, 0xbd, 0xeb, 0xd2, 0xed, 0xb5, 0x2b, 0x37, 0xf7, 0x30, 0xc6, 0xb0,
	0x92, 0xa3, 0x8e, 0xfa, 0x1e, 0x31, 0x58, 0x1c, 0x70, 0x44, 0xaa, 0xf4, 0x08, 0xea, 0x77, 0xd6,
	0x1e, 0x72, 0x44, 0x47, 0xbd, 0x54, 0xe3, 0x6f, 0xb8, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x49,
	0xa8, 0xe3, 0x4c, 0x2d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	//
	//以下 分别是 服务端 推送流， 客户端 推送流 ，双向流。
	GetStream(ctx context.Context, in *StreamReqData, opts ...grpc.CallOption) (Greeter_GetStreamClient, error)
	PutStream(ctx context.Context, opts ...grpc.CallOption) (Greeter_PutStreamClient, error)
	AllStream(ctx context.Context, opts ...grpc.CallOption) (Greeter_AllStreamClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetStream(ctx context.Context, in *StreamReqData, opts ...grpc.CallOption) (Greeter_GetStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/StorageMaintainerMessage.Greeter/GetStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterGetStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_GetStreamClient interface {
	Recv() (*StreamResData, error)
	grpc.ClientStream
}

type greeterGetStreamClient struct {
	grpc.ClientStream
}

func (x *greeterGetStreamClient) Recv() (*StreamResData, error) {
	m := new(StreamResData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) PutStream(ctx context.Context, opts ...grpc.CallOption) (Greeter_PutStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[1], "/StorageMaintainerMessage.Greeter/PutStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterPutStreamClient{stream}
	return x, nil
}

type Greeter_PutStreamClient interface {
	Send(*StreamReqData) error
	CloseAndRecv() (*StreamResData, error)
	grpc.ClientStream
}

type greeterPutStreamClient struct {
	grpc.ClientStream
}

func (x *greeterPutStreamClient) Send(m *StreamReqData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterPutStreamClient) CloseAndRecv() (*StreamResData, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamResData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) AllStream(ctx context.Context, opts ...grpc.CallOption) (Greeter_AllStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[2], "/StorageMaintainerMessage.Greeter/AllStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterAllStreamClient{stream}
	return x, nil
}

type Greeter_AllStreamClient interface {
	Send(*StreamReqData) error
	Recv() (*StreamResData, error)
	grpc.ClientStream
}

type greeterAllStreamClient struct {
	grpc.ClientStream
}

func (x *greeterAllStreamClient) Send(m *StreamReqData) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterAllStreamClient) Recv() (*StreamResData, error) {
	m := new(StreamResData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	//
	//以下 分别是 服务端 推送流， 客户端 推送流 ，双向流。
	GetStream(*StreamReqData, Greeter_GetStreamServer) error
	PutStream(Greeter_PutStreamServer) error
	AllStream(Greeter_AllStreamServer) error
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) GetStream(req *StreamReqData, srv Greeter_GetStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}
func (*UnimplementedGreeterServer) PutStream(srv Greeter_PutStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method PutStream not implemented")
}
func (*UnimplementedGreeterServer) AllStream(srv Greeter_AllStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method AllStream not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamReqData)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).GetStream(m, &greeterGetStreamServer{stream})
}

type Greeter_GetStreamServer interface {
	Send(*StreamResData) error
	grpc.ServerStream
}

type greeterGetStreamServer struct {
	grpc.ServerStream
}

func (x *greeterGetStreamServer) Send(m *StreamResData) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_PutStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).PutStream(&greeterPutStreamServer{stream})
}

type Greeter_PutStreamServer interface {
	SendAndClose(*StreamResData) error
	Recv() (*StreamReqData, error)
	grpc.ServerStream
}

type greeterPutStreamServer struct {
	grpc.ServerStream
}

func (x *greeterPutStreamServer) SendAndClose(m *StreamResData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterPutStreamServer) Recv() (*StreamReqData, error) {
	m := new(StreamReqData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_AllStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).AllStream(&greeterAllStreamServer{stream})
}

type Greeter_AllStreamServer interface {
	Send(*StreamResData) error
	Recv() (*StreamReqData, error)
	grpc.ServerStream
}

type greeterAllStreamServer struct {
	grpc.ServerStream
}

func (x *greeterAllStreamServer) Send(m *StreamResData) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterAllStreamServer) Recv() (*StreamReqData, error) {
	m := new(StreamReqData)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StorageMaintainerMessage.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStream",
			Handler:       _Greeter_GetStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutStream",
			Handler:       _Greeter_PutStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "AllStream",
			Handler:       _Greeter_AllStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "DeleteFromLocal_Stream.proto",
}
