// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DeleteFromLocal.proto

package StorageMaintainerMessage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//请求结构
type ReqData struct {
	StrChannelID         string   `protobuf:"bytes,1,opt,name=strChannelID,proto3" json:"strChannelID,omitempty"`
	StrRelativePath      string   `protobuf:"bytes,2,opt,name=strRelativePath,proto3" json:"strRelativePath,omitempty"`
	StrMountPoint        string   `protobuf:"bytes,3,opt,name=strMountPoint,proto3" json:"strMountPoint,omitempty"`
	StrDate              string   `protobuf:"bytes,4,opt,name=strDate,proto3" json:"strDate,omitempty"`
	StrRecordID          string   `protobuf:"bytes,5,opt,name=strRecordID,proto3" json:"strRecordID,omitempty"`
	NStartTime           int64    `protobuf:"varint,6,opt,name=nStartTime,proto3" json:"nStartTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqData) Reset()         { *m = ReqData{} }
func (m *ReqData) String() string { return proto.CompactTextString(m) }
func (*ReqData) ProtoMessage()    {}
func (*ReqData) Descriptor() ([]byte, []int) {
	return fileDescriptor_226b76d826ce9577, []int{0}
}

func (m *ReqData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqData.Unmarshal(m, b)
}
func (m *ReqData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqData.Marshal(b, m, deterministic)
}
func (m *ReqData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqData.Merge(m, src)
}
func (m *ReqData) XXX_Size() int {
	return xxx_messageInfo_ReqData.Size(m)
}
func (m *ReqData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqData proto.InternalMessageInfo

func (m *ReqData) GetStrChannelID() string {
	if m != nil {
		return m.StrChannelID
	}
	return ""
}

func (m *ReqData) GetStrRelativePath() string {
	if m != nil {
		return m.StrRelativePath
	}
	return ""
}

func (m *ReqData) GetStrMountPoint() string {
	if m != nil {
		return m.StrMountPoint
	}
	return ""
}

func (m *ReqData) GetStrDate() string {
	if m != nil {
		return m.StrDate
	}
	return ""
}

func (m *ReqData) GetStrRecordID() string {
	if m != nil {
		return m.StrRecordID
	}
	return ""
}

func (m *ReqData) GetNStartTime() int64 {
	if m != nil {
		return m.NStartTime
	}
	return 0
}

//返回结构
type ResData struct {
	StrChannelID         string   `protobuf:"bytes,1,opt,name=strChannelID,proto3" json:"strChannelID,omitempty"`
	NRespond             int32    `protobuf:"varint,2,opt,name=nRespond,proto3" json:"nRespond,omitempty"`
	StrRecordID          string   `protobuf:"bytes,3,opt,name=strRecordID,proto3" json:"strRecordID,omitempty"`
	StrDate              string   `protobuf:"bytes,4,opt,name=strDate,proto3" json:"strDate,omitempty"`
	StrMountPoint        string   `protobuf:"bytes,5,opt,name=strMountPoint,proto3" json:"strMountPoint,omitempty"`
	NStartTime           int64    `protobuf:"varint,6,opt,name=nStartTime,proto3" json:"nStartTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResData) Reset()         { *m = ResData{} }
func (m *ResData) String() string { return proto.CompactTextString(m) }
func (*ResData) ProtoMessage()    {}
func (*ResData) Descriptor() ([]byte, []int) {
	return fileDescriptor_226b76d826ce9577, []int{1}
}

func (m *ResData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResData.Unmarshal(m, b)
}
func (m *ResData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResData.Marshal(b, m, deterministic)
}
func (m *ResData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResData.Merge(m, src)
}
func (m *ResData) XXX_Size() int {
	return xxx_messageInfo_ResData.Size(m)
}
func (m *ResData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResData.DiscardUnknown(m)
}

var xxx_messageInfo_ResData proto.InternalMessageInfo

func (m *ResData) GetStrChannelID() string {
	if m != nil {
		return m.StrChannelID
	}
	return ""
}

func (m *ResData) GetNRespond() int32 {
	if m != nil {
		return m.NRespond
	}
	return 0
}

func (m *ResData) GetStrRecordID() string {
	if m != nil {
		return m.StrRecordID
	}
	return ""
}

func (m *ResData) GetStrDate() string {
	if m != nil {
		return m.StrDate
	}
	return ""
}

func (m *ResData) GetStrMountPoint() string {
	if m != nil {
		return m.StrMountPoint
	}
	return ""
}

func (m *ResData) GetNStartTime() int64 {
	if m != nil {
		return m.NStartTime
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqData)(nil), "StorageMaintainerMessage.ReqData")
	proto.RegisterType((*ResData)(nil), "StorageMaintainerMessage.ResData")
}

func init() { proto.RegisterFile("DeleteFromLocal.proto", fileDescriptor_226b76d826ce9577) }

var fileDescriptor_226b76d826ce9577 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x8d, 0x69, 0x1a, 0x1d, 0x15, 0x61, 0x41, 0x58, 0x7a, 0x90, 0x18, 0x3c, 0xe4, 0x94,
	0x83, 0x3e, 0x82, 0x41, 0x28, 0x18, 0xa8, 0x1b, 0x2f, 0x1e, 0xc7, 0x66, 0x48, 0x17, 0xd2, 0xdd,
	0xba, 0x3b, 0xfa, 0x92, 0x3e, 0x81, 0x6f, 0x23, 0x2e, 0x2a, 0xfd, 0x63, 0xb5, 0xa7, 0x65, 0xbe,
	0xf9, 0x58, 0xe6, 0xf7, 0xcd, 0xc0, 0x59, 0x45, 0x3d, 0x31, 0xdd, 0x3a, 0x3b, 0xbf, 0xb3, 0x53,
	0xec, 0xcb, 0x85, 0xb3, 0x6c, 0x85, 0x6c, 0xd8, 0x3a, 0xec, 0xa8, 0x46, 0x6d, 0x18, 0xb5, 0x21,
	0x57, 0x93, 0xf7, 0xd8, 0x51, 0xfe, 0x1e, 0x41, 0xaa, 0xe8, 0xb9, 0x42, 0x46, 0x91, 0xc3, 0xb1,
	0x67, 0x77, 0x33, 0x43, 0x63, 0xa8, 0x1f, 0x57, 0x32, 0xca, 0xa2, 0xe2, 0x50, 0xad, 0x68, 0xa2,
	0x80, 0x53, 0xcf, 0x4e, 0x51, 0x8f, 0xac, 0x5f, 0x69, 0x82, 0x3c, 0x93, 0xfb, 0xc1, 0xb6, 0x2e,
	0x8b, 0x4b, 0x38, 0xf1, 0xec, 0x6a, 0xfb, 0x62, 0x78, 0x62, 0xb5, 0x61, 0x19, 0x07, 0xdf, 0xaa,
	0x28, 0x24, 0xa4, 0x9e, 0x5d, 0x85, 0x4c, 0x72, 0x10, 0xfa, 0xdf, 0xa5, 0xc8, 0xe0, 0x28, 0x7c,
	0x39, 0xb5, 0xae, 0x1d, 0x57, 0x32, 0x09, 0xdd, 0x65, 0x49, 0x9c, 0x03, 0x98, 0x86, 0xd1, 0xf1,
	0x83, 0x9e, 0x93, 0x1c, 0x66, 0x51, 0x11, 0xab, 0x25, 0x25, 0x7f, 0x0b, 0x6c, 0x7e, 0x67, 0xb6,
	0x11, 0x1c, 0x18, 0x45, 0x7e, 0x61, 0x4d, 0x1b, 0xa0, 0x12, 0xf5, 0x53, 0xaf, 0x4f, 0x13, 0x6f,
	0x4e, 0xb3, 0x9d, 0x64, 0x23, 0x89, 0xe4, 0xb7, 0x24, 0xfe, 0xa1, 0xb9, 0x7a, 0x84, 0x41, 0x43,
	0xa6, 0x15, 0xf7, 0x90, 0x7e, 0xbe, 0xb5, 0xef, 0xc4, 0x45, 0xb9, 0x6d, 0xaf, 0xe5, 0xd7, 0x4e,
	0x47, 0x7f, 0x5a, 0x42, 0x34, 0xf9, 0xde, 0xd3, 0x30, 0x5c, 0xc9, 0xf5, 0x47, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x8b, 0xf3, 0xa3, 0x60, 0x3e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SendClient is the client API for Send service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendClient interface {
	SendMsg(ctx context.Context, in *ReqData, opts ...grpc.CallOption) (*ResData, error)
}

type sendClient struct {
	cc *grpc.ClientConn
}

func NewSendClient(cc *grpc.ClientConn) SendClient {
	return &sendClient{cc}
}

func (c *sendClient) SendMsg(ctx context.Context, in *ReqData, opts ...grpc.CallOption) (*ResData, error) {
	out := new(ResData)
	err := c.cc.Invoke(ctx, "/StorageMaintainerMessage.Send/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendServer is the server API for Send service.
type SendServer interface {
	SendMsg(context.Context, *ReqData) (*ResData, error)
}

// UnimplementedSendServer can be embedded to have forward compatible implementations.
type UnimplementedSendServer struct {
}

func (*UnimplementedSendServer) SendMsg(ctx context.Context, req *ReqData) (*ResData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}

func RegisterSendServer(s *grpc.Server, srv SendServer) {
	s.RegisterService(&_Send_serviceDesc, srv)
}

func _Send_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageMaintainerMessage.Send/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendServer).SendMsg(ctx, req.(*ReqData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Send_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StorageMaintainerMessage.Send",
	HandlerType: (*SendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMsg",
			Handler:    _Send_SendMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "DeleteFromLocal.proto",
}
